version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - kafka-net
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
  
  kafka-broker:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-broker
    container_name: kafka-broker
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    expose:
     - "9093"
    command: sh -c "((sleep 15 && kafka-topics --bootstrap-server kafka-broker:9093 --create --replication-factor $REPLICATION_FACTOR --partitions $PARTITIONS --topic $TOPIC)&) && /etc/confluent/docker/run ">
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-broker:9093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka-ui
    depends_on:
      kafka-broker:
        condition: service_started
    networks:
      - kafka-net
    ports:
      - "8090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker:9093"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD_USER
    volumes:
      - mongodb_data:/data/db
      - ./mongo/mongodb_config:/data/configdb
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - kafka-net

  mongo-express:
    image: mongo-express:latest
    hostname: mongoexpress
    container_name: mongoexpress
    restart: no
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD_USER
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASSWORD_USER@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: $EXPRESS_USER
      ME_CONFIG_BASICAUTH_PASSWORD: $EXPRESS_PASSWORD
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - kafka-net

  producer:
    hostname: producer
    container_name: producer
    build:
      context: ./producer
    volumes:
      - ./producer:/app
    depends_on:
      kafka-broker:
        condition: service_started
    networks:
      - kafka-net

  consumer:
    hostname: consumer
    container_name: consumer
    build:
      context: ./consumer
    volumes:
      - ./consumer:/app
    depends_on:
      kafka-broker:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - kafka-net

volumes:
  mongodb_data:

networks:
  kafka-net:
